version: '3.7'

services:
  grafana:
      image: grafana/grafana:latest
      container_name: grafanaIot
      ports:
        - 3001:3000
      restart: unless-stopped
      environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      volumes:
        - grafana-volume:/var/lib/grafana

  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-iot-volume:/data/db

volumes:
  mongodb-iot-volume:
  grafana-volume: