version: '3.7'

services:
  grafana:
      image: grafana/grafana:latest
      container_name: grafanaIot
      ports:
        - 3001:3000
      restart: unless-stopped
      environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      volumes:
        - grafana-volume:/var/lib/grafana
      networks:
        - grafana-influxdb-net
  
  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb_volume:/var/lib/influxdb2
    networks:
      - grafana-influxdb-net

volumes:
  influxdb_volume:
  grafana-volume:

networks:
  grafana-influxdb-net:
