version: '3.7'

services:
  grafana:
      image: grafana/grafana:latest
      ports:
        - 3001:3000
      restart: unless-stopped
      volumes:
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - grafana-volume:/var/lib/grafana

  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-iot-volume:/data/db

volumes:
  mongodb-iot-volume:
  grafana-volume: