version: '3.7'

services:
  grafana:
      image: grafana/grafana:latest
      container_name: grafanaIot
      ports:
        - 3001:3000
      restart: unless-stopped
      environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      volumes:
        - grafana-volume:/var/lib/grafana
      networks:
        - grafana-influxdb-net
  
  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - INFLUXDB_DB=testInfluxDB
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
    ports:
      - 8086:8086 #TCP
      - 8083:8083 #Web
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - grafana-influxdb-net

volumes:
  influxdb_data:
  grafana-volume:

networks:
  grafana-influxdb-net:
